Add PPP to ramaven.md
AY2122S1-CS2103T-T15-1/tp pull request #318
Opened 2021-11-06 17:05 UTC by ramaven

### Summary

Add PPP to ramaven.md

### Checks

- [ ] Link PR to issue
- [ ] Add Reviewer
- [ ] Pass CI

2021-11-06 17:45 UTC, simonjulianl commented on docs/team/ramaven.md
> +  * Reviewed and approved some team members' PRs for merging.
You might wanna put some examples of those PRs

2021-11-06 17:47 UTC, simonjulianl commented on docs/team/ramaven.md
> +    * Credits: This heavily uses JavaFx.
```suggestion
    * Credits: This heavily uses CSS feature of JavaFx. 
```

2021-11-06 17:50 UTC, simonjulianl commented on docs/team/ramaven.md
> +* **New feature**: Develop datetime parser
Erm, sorry about this but I replace the parser using localDateTime function which takes like 6 lines. So yeah, you might want to rephrase this as it is not there anymore (like initial skeleton of datetime parser or sth along this line)

2021-11-06 17:58 UTC, simonjulianl requested changes
Can help to check my comments

2021-11-07 04:26 UTC, ramaven commented
> Can help to check my comments

Yup done

2021-11-07 04:57 UTC, simonjulianl commented on docs/team/ramaven.md
> +---
wait why do you need two PRs for this ?

2021-11-07 04:58 UTC, simonjulianl approved these changes
LGTM btw, and you wanna close the other pr

2021-11-07 04:59 UTC, merged